import type { Characteristics, Investigator } from './types'
import { CHARACTERISTIC_NAMES } from './types'
import { derivedStats } from './derived'
import { occupationById } from './occupations'
import { resolveSkill, skillBase } from './skills'
import { halfValue, fifthValue } from './characteristics'
import { validateAllocation } from './allocation'
import { finances1920s, formatDollars } from './finance'
import { gearSpending } from './gear'
import type { DeductionSplit, EduCheckResult } from './age'

/**
 * Everything needed to restore a creation session losslessly — mirrors the
 * persisted store state minus the wizard step.
 */
export interface CharacterFileData {
  genMethod: 'roll' | 'pointbuy' | 'manual'
  baseCharacteristics: Characteristics
  hasRolled: boolean
  deductionSplit: DeductionSplit
  eduChecks: EduCheckResult[]
  luckRolls: number[]
  investigator: Investigator
}

const MARKER = 'coc-investigator-data:v1'

const BACKSTORY_LABELS: [keyof Investigator['backstory'] & string, string][] = [
  ['ideology', 'Ideology / Beliefs'],
  ['significantPeople', 'Significant People'],
  ['meaningfulLocations', 'Meaningful Locations'],
  ['treasuredPossessions', 'Treasured Possessions'],
  ['traits', 'Traits'],
]

/**
 * Render a character file: a human-readable Markdown sheet with the full
 * machine-readable state embedded in an HTML comment, so the file can be
 * re-imported losslessly. "--" never legally occurs outside JSON strings, so
 * escaping it as \u002d\u002d keeps the surrounding HTML comment intact and
 * JSON.parse restores the original text.
 */
export function characterFileMarkdown(data: CharacterFileData): string {
  const inv = data.investigator
  const chars = inv.characteristics
  const derived = derivedStats(chars, inv.age)
  const { creditRating } = validateAllocation(inv)
  const fin = finances1920s(creditRating)
  const { spent } = gearSpending(inv.gear, fin)
  const occupation = inv.occupationId ? occupationById(inv.occupationId) : undefined

  const lines: string[] = []
  lines.push(`# ${inv.name || 'Unnamed Investigator'}${occupation ? ` — ${occupation.name}` : ''}`)
  lines.push('')
  lines.push('Call of Cthulhu 7e investigator (1920s).')
  lines.push('')
  const basics: string[] = []
  if (inv.player) basics.push(`**Player:** ${inv.player}`)
  basics.push(`**Age:** ${inv.age}`)
  if (inv.sex) basics.push(`**Sex:** ${inv.sex}`)
  if (inv.birthplace) basics.push(`**Birthplace:** ${inv.birthplace}`)
  if (inv.residence) basics.push(`**Residence:** ${inv.residence}`)
  lines.push(basics.join(' · '))
  lines.push('')
  lines.push('## Characteristics')
  lines.push('')
  lines.push(`| ${CHARACTERISTIC_NAMES.join(' | ')} | Luck |`)
  lines.push(`|${CHARACTERISTIC_NAMES.map(() => '----').join('|')}|----|`)
  lines.push(`| ${CHARACTERISTIC_NAMES.map((n) => chars[n]).join(' | ')} | ${inv.luck} |`)
  lines.push('')
  lines.push(
    `**HP** ${derived.hitPoints} · **MP** ${derived.magicPoints} · **SAN** ${derived.sanity} · ` +
      `**Damage Bonus** ${derived.damageBonus} · **Build** ${derived.build} · **MOV** ${derived.move}`,
  )
  lines.push('')
  lines.push('## Skills')
  lines.push('')
  lines.push('| Skill | Total | ½ | ⅕ |')
  lines.push('|----|----|----|----|')
  const rows = inv.skills
    .filter((a) => a.occupationPoints + a.personalPoints > 0 || a.skillId === 'credit-rating')
    .map((a) => {
      const def = resolveSkill(inv.customSkills, a.skillId)
      const name = a.spec ? `${def.name} (${a.spec})` : def.name
      const total = skillBase(def, chars) + a.occupationPoints + a.personalPoints
      return { name, total }
    })
    .sort((a, b) => a.name.localeCompare(b.name))
  for (const r of rows) lines.push(`| ${r.name} | ${r.total} | ${halfValue(r.total)} | ${fifthValue(r.total)} |`)
  lines.push('')
  const backstory = BACKSTORY_LABELS.filter(([key]) => inv.backstory[key])
  if (backstory.length > 0) {
    lines.push('## Backstory')
    lines.push('')
    for (const [key, label] of backstory) {
      const star = inv.backstory.keyConnection === key ? ' ★' : ''
      lines.push(`**${label}:**${star} ${inv.backstory[key]}`)
      lines.push('')
    }
  }
  lines.push('## Gear & Finances')
  lines.push('')
  for (const item of inv.gear) lines.push(`- ${item}`)
  if (inv.gear.length === 0) lines.push('—')
  lines.push('')
  lines.push(
    `Credit Rating ${creditRating} — ${fin.label}. Spending level ${formatDollars(fin.spendingLevel)}, ` +
      `cash ${formatDollars(fin.cash)}, assets ${fin.assetsNote ?? formatDollars(fin.assets)}.` +
      (spent > 0 ? ` Spent on gear ${formatDollars(spent)}.` : ''),
  )
  lines.push('')
  if (inv.notes) {
    lines.push('## Notes')
    lines.push('')
    lines.push(inv.notes)
    lines.push('')
  }
  lines.push('---')
  lines.push('')
  lines.push('*Generated by the CoC Investigator Creator. Re-upload this file there to continue editing.*')
  lines.push('')
  const json = JSON.stringify(data, null, 2).replace(/--/g, '\\u002d\\u002d')
  lines.push(`<!-- ${MARKER}`)
  lines.push(json)
  lines.push('-->')
  lines.push('')
  return lines.join('\n')
}

/** Parse a character file back into creator state. Throws with a readable message. */
export function parseCharacterFile(text: string): CharacterFileData {
  const match = new RegExp(`<!--\\s*${MARKER}\\n([\\s\\S]*?)\\n-->`).exec(text)
  if (!match) {
    throw new Error('No investigator data found — is this a character file downloaded from this app?')
  }
  let data: CharacterFileData
  try {
    data = JSON.parse(match[1]) as CharacterFileData
  } catch {
    throw new Error('The embedded investigator data is not valid JSON — was the file edited?')
  }
  const inv = data.investigator
  if (!inv || typeof inv !== 'object') throw new Error('Character file has no investigator record.')
  for (const name of CHARACTERISTIC_NAMES) {
    if (typeof inv.characteristics?.[name] !== 'number' || typeof data.baseCharacteristics?.[name] !== 'number') {
      throw new Error(`Character file is missing the ${name} characteristic.`)
    }
  }
  if (!Array.isArray(inv.skills) || !Array.isArray(inv.gear)) {
    throw new Error('Character file is missing skills or gear lists.')
  }
  if (inv.occupationId) occupationById(inv.occupationId) // throws on unknown occupations
  inv.customSkills ??= []
  data.eduChecks ??= []
  data.luckRolls ??= []
  data.deductionSplit ??= {}
  return data
}
