import { INTERPERSONAL_SKILL_IDS, type Occupation, type OccupationSkillSlot } from './types'

const interpersonal = (count: number): OccupationSkillSlot => ({
  kind: 'choice',
  count,
  from: INTERPERSONAL_SKILL_IDS,
  label: count === 1 ? 'one interpersonal skill' : `${count} interpersonal skills`,
})

const fixed = (skillId: string, spec?: string): OccupationSkillSlot =>
  spec ? { kind: 'fixed', skillId, spec } : { kind: 'fixed', skillId }

const oneOf = (label: string, ...from: string[]): OccupationSkillSlot => ({
  kind: 'choice',
  count: 1,
  from,
  label,
})

const any = (count: number): OccupationSkillSlot => ({ kind: 'any', count })

/**
 * Occupations for the 1920s era: the core-rulebook list plus the extended
 * Investigator Handbook list (near-duplicate variants merged). Descriptions
 * and contact notes are our own summaries — no rulebook text. Formulas,
 * credit-rating ranges and skill slots follow the published occupations;
 * spot-check details against your copy and correct here if needed.
 * Every occupation also buys Credit Rating from occupation points, within
 * the listed range.
 */
export const OCCUPATIONS: readonly Occupation[] = [
  {
    id: 'accountant',
    name: 'Accountant',
    description: 'Keeper of ledgers and finder of financial irregularities.',
    points: { kind: 'edu4' },
    creditRating: { min: 30, max: 70 },
    slots: [fixed('accounting'), fixed('law'), fixed('library-use'), fixed('listen'), interpersonal(1), fixed('psychology'), fixed('spot-hidden'), any(1)],
    suggestedContacts: 'Business associates, lawyers, financial sector colleagues.',
  },
  {
    id: 'acrobat',
    name: 'Acrobat',
    description: 'Circus or vaudeville tumbler in superb physical condition.',
    points: { kind: 'edu2plus', other: ['DEX'] },
    creditRating: { min: 9, max: 20 },
    slots: [fixed('climb'), fixed('dodge'), fixed('jump'), fixed('swim'), fixed('spot-hidden'), fixed('throw'), any(2)],
    suggestedContacts: 'Circus folk, carnival troupes, athletic clubs.',
  },
  {
    id: 'actor',
    name: 'Actor',
    description: 'Stage or screen performer chasing the limelight.',
    points: { kind: 'edu2plus', other: ['APP'] },
    creditRating: { min: 9, max: 40 },
    slots: [fixed('art-craft', 'Acting'), fixed('disguise'), fixed('history'), interpersonal(2), fixed('psychology'), any(2)],
    suggestedContacts: 'Theatre and film people, newspapers, critics, agents.',
  },
  {
    id: 'agency-detective',
    name: 'Agency Detective',
    description: 'Operative of a large detective agency, from guard work to manhunts.',
    points: { kind: 'edu2plus', other: ['DEX', 'STR'] },
    creditRating: { min: 20, max: 45 },
    slots: [interpersonal(1), fixed('fighting-brawl'), fixed('firearms-handgun'), fixed('law'), fixed('library-use'), fixed('psychology'), fixed('stealth'), fixed('track')],
    suggestedContacts: 'Agency colleagues, police, clients, informants.',
  },
  {
    id: 'alienist',
    name: 'Alienist',
    description: 'Early psychiatrist treating diseases of the mind.',
    points: { kind: 'edu4' },
    creditRating: { min: 10, max: 60 },
    slots: [fixed('law'), fixed('listen'), fixed('medicine'), fixed('language-other'), fixed('psychoanalysis'), fixed('psychology'), oneOf('Science (Biology) or Science (Chemistry)', 'science'), any(1)],
    suggestedContacts: 'Asylums, medical colleagues, patients and their families.',
  },
  {
    id: 'animal-trainer',
    name: 'Animal Trainer',
    description: 'Trainer of beasts for circus, film or private menageries.',
    points: { kind: 'edu2plus', other: ['APP', 'POW'] },
    creditRating: { min: 10, max: 40 },
    slots: [fixed('animal-handling'), fixed('jump'), fixed('listen'), fixed('natural-world'), fixed('science', 'Zoology'), fixed('stealth'), fixed('track'), any(1)],
    suggestedContacts: 'Zoos, circuses, film studios, wealthy exotic-pet owners.',
  },
  {
    id: 'antiquarian',
    name: 'Antiquarian',
    description: 'Collector and student of old and curious things.',
    points: { kind: 'edu4' },
    creditRating: { min: 30, max: 70 },
    slots: [fixed('appraise'), fixed('art-craft'), fixed('history'), fixed('library-use'), fixed('language-other'), interpersonal(1), fixed('spot-hidden'), any(1)],
    suggestedContacts: 'Booksellers, antique dealers, historical societies, museums.',
  },
  {
    id: 'antique-dealer',
    name: 'Antique Dealer',
    description: 'Trader in furniture, curios and estate treasures.',
    points: { kind: 'edu4' },
    creditRating: { min: 30, max: 50 },
    slots: [fixed('accounting'), fixed('appraise'), fixed('drive-auto'), interpersonal(2), fixed('history'), fixed('library-use'), fixed('navigate')],
    suggestedContacts: 'Collectors, auction houses, estate lawyers, smugglers.',
  },
  {
    id: 'archaeologist',
    name: 'Archaeologist',
    description: 'Field scholar excavating the remains of vanished cultures.',
    points: { kind: 'edu4' },
    creditRating: { min: 10, max: 40 },
    slots: [
      fixed('appraise'),
      fixed('archaeology'),
      fixed('history'),
      fixed('language-other'),
      fixed('library-use'),
      fixed('spot-hidden'),
      fixed('mechanical-repair'),
      oneOf('Navigate or a Science (e.g. Chemistry, Geology)', 'navigate', 'science'),
    ],
    suggestedContacts: 'Museums, universities, patrons, foreign officials, dig crews.',
  },
  {
    id: 'architect',
    name: 'Architect',
    description: 'Designer of buildings, from bungalows to skyscrapers.',
    points: { kind: 'edu4' },
    creditRating: { min: 30, max: 70 },
    slots: [fixed('accounting'), fixed('art-craft', 'Technical Drawing'), fixed('law'), fixed('language-own'), fixed('library-use'), fixed('persuade'), fixed('psychology'), any(1)],
    suggestedContacts: 'Building contractors, city planners, engineers, wealthy clients.',
  },
  {
    id: 'artist',
    name: 'Artist',
    description: 'Painter, sculptor or other creator of works of art.',
    points: { kind: 'edu2plus', other: ['DEX', 'POW'] },
    creditRating: { min: 9, max: 50 },
    slots: [fixed('art-craft'), oneOf('History or Natural World', 'history', 'natural-world'), interpersonal(1), fixed('language-other'), fixed('psychology'), fixed('spot-hidden'), any(2)],
    suggestedContacts: 'Art galleries, critics, wealthy patrons, the advertising industry.',
  },
  {
    id: 'asylum-attendant',
    name: 'Asylum Attendant',
    description: 'Keeper of order on the wards of a mental institution.',
    points: { kind: 'edu2plus', other: ['DEX', 'STR'] },
    creditRating: { min: 8, max: 20 },
    slots: [fixed('dodge'), fixed('fighting-brawl'), fixed('first-aid'), interpersonal(2), fixed('listen'), fixed('psychology'), fixed('stealth')],
    suggestedContacts: 'Asylum staff, doctors, patients and their families, pharmacists.',
  },
  {
    id: 'athlete',
    name: 'Athlete',
    description: 'Professional or gentleman sportsman in peak condition.',
    points: { kind: 'edu2plus', other: ['DEX', 'STR'] },
    creditRating: { min: 9, max: 70 },
    slots: [fixed('climb'), fixed('jump'), fixed('fighting-brawl'), fixed('ride'), interpersonal(1), fixed('swim'), fixed('throw'), any(1)],
    suggestedContacts: 'Sports clubs, sportswriters, other athletes, coaches.',
  },
  {
    id: 'author',
    name: 'Author',
    description: 'Writer of novels, stories or verse, often on the trail of inspiration.',
    points: { kind: 'edu4' },
    creditRating: { min: 9, max: 30 },
    slots: [fixed('art-craft', 'Literature'), fixed('history'), fixed('library-use'), oneOf('Natural World or Occult', 'natural-world', 'occult'), fixed('language-other'), fixed('language-own'), fixed('psychology'), any(1)],
    suggestedContacts: 'Publishers, editors, critics, other writers.',
  },
  {
    id: 'bank-robber',
    name: 'Bank Robber',
    description: 'Armed specialist in the swift withdrawal of other people’s money.',
    points: { kind: 'edu2plus', other: ['DEX', 'STR'] },
    creditRating: { min: 5, max: 75 },
    slots: [
      fixed('drive-auto'),
      oneOf('Electrical or Mechanical Repair', 'electrical-repair', 'mechanical-repair'),
      fixed('fighting-brawl'),
      fixed('firearms-handgun'),
      fixed('intimidate'),
      fixed('locksmith'),
      fixed('operate-heavy-machinery'),
      any(1),
    ],
    suggestedContacts: 'Other gang members, fences, corrupt lawyers, ex-cellmates.',
  },
  {
    id: 'bartender',
    name: 'Bartender',
    description: 'Keeper of the speakeasy tap and hearer of every secret in town.',
    points: { kind: 'edu2plus', other: ['APP'] },
    creditRating: { min: 8, max: 25 },
    slots: [fixed('accounting'), interpersonal(2), fixed('fighting-brawl'), fixed('listen'), fixed('psychology'), fixed('spot-hidden'), any(1)],
    suggestedContacts: 'Regulars, bootleggers, local police, organized crime.',
  },
  {
    id: 'big-game-hunter',
    name: 'Big Game Hunter',
    description: 'Professional tracker of dangerous beasts on distant continents.',
    points: { kind: 'edu2plus', other: ['DEX', 'STR'] },
    creditRating: { min: 20, max: 50 },
    slots: [
      fixed('firearms-rifle-shotgun'),
      oneOf('Listen or Spot Hidden', 'listen', 'spot-hidden'),
      fixed('natural-world'),
      fixed('navigate'),
      oneOf('Language (Other) or Survival', 'language-other', 'survival'),
      oneOf('Science (Biology, Botany or Zoology)', 'science'),
      fixed('stealth'),
      fixed('track'),
    ],
    suggestedContacts: 'Foreign guides, game wardens, wealthy clients, zoos, museums.',
  },
  {
    id: 'book-dealer',
    name: 'Book Dealer',
    description: 'Seller of rare volumes, some best left unsold.',
    points: { kind: 'edu4' },
    creditRating: { min: 20, max: 40 },
    slots: [fixed('accounting'), fixed('appraise'), fixed('drive-auto'), fixed('history'), fixed('library-use'), oneOf('Language (Own or Other)', 'language-own', 'language-other'), interpersonal(1), any(1)],
    suggestedContacts: 'Bibliophiles, libraries, universities, private collectors.',
  },
  {
    id: 'bootlegger',
    name: 'Bootlegger / Thug',
    description: 'Muscle and liquor-runner for the outfits Prohibition made rich.',
    points: { kind: 'edu2plus', other: ['STR'] },
    creditRating: { min: 5, max: 30 },
    slots: [fixed('drive-auto'), fixed('fighting-brawl'), fixed('firearms-handgun'), interpersonal(1), fixed('listen'), fixed('psychology'), fixed('spot-hidden'), fixed('stealth')],
    suggestedContacts: 'Organized crime, street gangs, speakeasies, corrupt cops.',
  },
  {
    id: 'bounty-hunter',
    name: 'Bounty Hunter',
    description: 'Tracker of bail-jumpers and fugitives, for a price.',
    points: { kind: 'edu2plus', other: ['DEX', 'STR'] },
    creditRating: { min: 9, max: 30 },
    slots: [fixed('drive-auto'), fixed('electrical-repair'), oneOf('Fighting or Firearms', 'fighting-brawl', 'firearms-handgun'), interpersonal(1), fixed('law'), fixed('psychology'), fixed('track'), fixed('stealth')],
    suggestedContacts: 'Bail bondsmen, local police, informants, skip-tracers.',
  },
  {
    id: 'boxer',
    name: 'Boxer / Wrestler',
    description: 'Prizefighter earning purses in the ring — or in less legal venues.',
    points: { kind: 'edu2plus', other: ['STR'] },
    creditRating: { min: 9, max: 60 },
    slots: [fixed('dodge'), fixed('fighting-brawl'), fixed('intimidate'), fixed('jump'), fixed('psychology'), fixed('spot-hidden'), any(2)],
    suggestedContacts: 'Promoters, gamblers, organized crime, sportswriters.',
  },
  {
    id: 'burglar',
    name: 'Burglar',
    description: 'Practitioner of quiet entry and quieter exits.',
    points: { kind: 'edu2plus', other: ['DEX'] },
    creditRating: { min: 5, max: 40 },
    slots: [fixed('appraise'), fixed('climb'), oneOf('Electrical or Mechanical Repair', 'electrical-repair', 'mechanical-repair'), fixed('listen'), fixed('locksmith'), fixed('sleight-of-hand'), fixed('stealth'), fixed('spot-hidden')],
    suggestedContacts: 'Fences, other criminals, locksmiths, pawn shops.',
  },
  {
    id: 'butler',
    name: 'Butler / Valet / Maid',
    description: 'Discreet servant who knows the household better than its master.',
    points: { kind: 'edu4' },
    creditRating: { min: 9, max: 40 },
    slots: [oneOf('Accounting or Appraise', 'accounting', 'appraise'), fixed('art-craft'), fixed('first-aid'), fixed('listen'), fixed('psychology'), interpersonal(2), any(1)],
    suggestedContacts: 'Household staff networks, tradespeople, the family’s circle.',
  },
  {
    id: 'chauffeur',
    name: 'Chauffeur',
    description: 'Private driver to the wealthy and the powerful.',
    points: { kind: 'edu2plus', other: ['DEX'] },
    creditRating: { min: 10, max: 40 },
    slots: [fixed('drive-auto'), interpersonal(2), fixed('listen'), fixed('mechanical-repair'), fixed('navigate'), fixed('spot-hidden'), any(1)],
    suggestedContacts: 'Wealthy employers, other drivers, garages, hotel staff.',
  },
  {
    id: 'clergy',
    name: 'Member of the Clergy',
    description: 'Ordained minister, priest or rabbi tending a flock.',
    points: { kind: 'edu4' },
    creditRating: { min: 9, max: 60 },
    slots: [fixed('accounting'), fixed('history'), fixed('library-use'), fixed('listen'), fixed('language-other'), interpersonal(1), fixed('psychology'), any(1)],
    suggestedContacts: 'Church hierarchy, local congregations, community leaders.',
  },
  {
    id: 'confidence-trickster',
    name: 'Confidence Trickster',
    description: 'Silver-tongued architect of swindles great and small.',
    points: { kind: 'edu2plus', other: ['APP'] },
    creditRating: { min: 10, max: 65 },
    slots: [fixed('appraise'), fixed('art-craft', 'Acting'), oneOf('Law or Language (Other)', 'law', 'language-other'), fixed('listen'), interpersonal(2), fixed('psychology'), fixed('sleight-of-hand')],
    suggestedContacts: 'Other grifters, gamblers, marks with money, crooked lawyers.',
  },
  {
    id: 'cowboy',
    name: 'Cowboy / Cowgirl',
    description: 'Ranch hand of the fading West, at home in the saddle.',
    points: { kind: 'edu2plus', other: ['DEX', 'STR'] },
    creditRating: { min: 9, max: 20 },
    slots: [
      fixed('dodge'),
      oneOf('Fighting or Firearms', 'fighting-brawl', 'firearms-rifle-shotgun'),
      oneOf('First Aid or Natural World', 'first-aid', 'natural-world'),
      fixed('jump'),
      fixed('ride'),
      fixed('survival'),
      fixed('throw'),
      fixed('track'),
    ],
    suggestedContacts: 'Ranchers, rodeo circuit, cattle buyers, rural lawmen.',
  },
  {
    id: 'craftsperson',
    name: 'Craftsperson',
    description: 'Skilled maker — carpenter, cobbler, smith or potter.',
    points: { kind: 'edu2plus', other: ['DEX'] },
    creditRating: { min: 10, max: 40 },
    slots: [fixed('accounting'), fixed('art-craft'), fixed('mechanical-repair'), fixed('natural-world'), fixed('spot-hidden'), any(3)],
    suggestedContacts: 'Suppliers, customers, guild or union members, shopkeepers.',
  },
  {
    id: 'criminal',
    name: 'Criminal',
    description: 'Burglar, con artist, bootlegger or freelance villain.',
    points: { kind: 'edu2plus', other: ['DEX', 'STR'] },
    creditRating: { min: 5, max: 65 },
    slots: [
      interpersonal(1),
      fixed('psychology'),
      fixed('spot-hidden'),
      fixed('stealth'),
      {
        kind: 'choice',
        count: 4,
        from: ['appraise', 'disguise', 'fighting-brawl', 'firearms-handgun', 'locksmith', 'mechanical-repair', 'sleight-of-hand'],
        label: 'four specialisms of the trade',
      },
    ],
    suggestedContacts: 'The underworld, fences, corrupt officials, other criminals.',
  },
  {
    id: 'cult-leader',
    name: 'Cult Leader',
    description: 'Charismatic shepherd of an unorthodox flock.',
    points: { kind: 'edu2plus', other: ['APP'] },
    creditRating: { min: 30, max: 60 },
    slots: [fixed('accounting'), interpersonal(2), fixed('occult'), fixed('psychology'), fixed('spot-hidden'), any(2)],
    suggestedContacts: 'Devoted followers, wealthy patrons, curious journalists.',
  },
  {
    id: 'dilettante',
    name: 'Dilettante',
    description: 'Person of independent means free to pursue their whims.',
    points: { kind: 'edu2plus', other: ['APP'] },
    creditRating: { min: 50, max: 99 },
    slots: [fixed('art-craft'), fixed('firearms-handgun'), fixed('language-other'), fixed('ride'), interpersonal(1), any(3)],
    suggestedContacts: 'High society, old family friends, artists and hangers-on.',
  },
  {
    id: 'diver',
    name: 'Diver',
    description: 'Salvage or sponge diver working the deeps in canvas and brass.',
    points: { kind: 'edu2plus', other: ['DEX'] },
    creditRating: { min: 9, max: 30 },
    slots: [fixed('diving'), fixed('first-aid'), fixed('mechanical-repair'), fixed('pilot', 'Boat'), fixed('science', 'Biology'), fixed('spot-hidden'), fixed('swim'), any(1)],
    suggestedContacts: 'Salvage companies, harbormasters, marine insurers, smugglers.',
  },
  {
    id: 'doctor',
    name: 'Doctor of Medicine',
    description: 'Physician, surgeon or medical researcher.',
    points: { kind: 'edu4' },
    creditRating: { min: 30, max: 80 },
    slots: [fixed('first-aid'), fixed('language-other', 'Latin'), fixed('medicine'), fixed('psychology'), fixed('science', 'Biology'), fixed('science', 'Pharmacy'), any(2)],
    suggestedContacts: 'Patients, hospital staff, medical colleagues, nurses.',
  },
  {
    id: 'drifter',
    name: 'Drifter',
    description: 'Wanderer living hand to mouth on the road.',
    points: { kind: 'edu2plus', other: ['APP', 'DEX', 'STR'] },
    creditRating: { min: 0, max: 5 },
    slots: [fixed('climb'), fixed('jump'), fixed('listen'), fixed('navigate'), interpersonal(1), fixed('stealth'), any(2)],
    suggestedContacts: 'Other drifters, freight yard workers, rural folk met on the road.',
  },
  {
    id: 'editor',
    name: 'Editor',
    description: 'Newsroom taskmaster deciding what the public gets to read.',
    points: { kind: 'edu4' },
    creditRating: { min: 10, max: 30 },
    slots: [fixed('accounting'), fixed('history'), interpersonal(2), fixed('language-own'), fixed('psychology'), fixed('spot-hidden'), any(1)],
    suggestedContacts: 'Reporters, publishers, politicians, advertisers, printers.',
  },
  {
    id: 'elected-official',
    name: 'Elected Official',
    description: 'Alderman, mayor or congressman with a machine behind them.',
    points: { kind: 'edu2plus', other: ['APP'] },
    creditRating: { min: 50, max: 90 },
    slots: [fixed('charm'), fixed('history'), fixed('intimidate'), fixed('fast-talk'), fixed('listen'), fixed('language-own'), fixed('persuade'), fixed('psychology')],
    suggestedContacts: 'Party machine, donors, the press, bureaucrats, unions.',
  },
  {
    id: 'engineer',
    name: 'Engineer',
    description: 'Designer and builder of machines, structures and systems.',
    points: { kind: 'edu4' },
    creditRating: { min: 30, max: 60 },
    slots: [fixed('art-craft', 'Technical Drawing'), fixed('electrical-repair'), fixed('library-use'), fixed('mechanical-repair'), fixed('operate-heavy-machinery'), fixed('science', 'Engineering'), any(2)],
    suggestedContacts: 'Industrialists, military contacts, city planners, workshops.',
  },
  {
    id: 'entertainer',
    name: 'Entertainer',
    description: 'Singer, dancer or vaudeville performer.',
    points: { kind: 'edu2plus', other: ['APP'] },
    creditRating: { min: 9, max: 70 },
    slots: [fixed('art-craft', 'Acting'), fixed('disguise'), interpersonal(2), fixed('listen'), fixed('psychology'), any(2)],
    suggestedContacts: 'Theatre people, film studios, newspapers, organized crime.',
  },
  {
    id: 'explorer',
    name: 'Explorer',
    description: 'Chartered adventurer pushing into the blank spaces of the map.',
    points: { kind: 'edu2plus', other: ['APP', 'DEX', 'STR'] },
    creditRating: { min: 55, max: 80 },
    slots: [
      oneOf('Climb or Swim', 'climb', 'swim'),
      fixed('firearms-rifle-shotgun'),
      fixed('history'),
      fixed('jump'),
      fixed('natural-world'),
      fixed('navigate'),
      fixed('language-other'),
      fixed('survival'),
    ],
    suggestedContacts: 'Geographic societies, museums, patrons, foreign guides, the press.',
  },
  {
    id: 'farmer',
    name: 'Farmer',
    description: 'Owner or worker of a farm, wise in the ways of land and weather.',
    points: { kind: 'edu2plus', other: ['DEX', 'STR'] },
    creditRating: { min: 9, max: 30 },
    slots: [fixed('art-craft', 'Farming'), fixed('drive-auto'), interpersonal(1), fixed('mechanical-repair'), fixed('natural-world'), fixed('operate-heavy-machinery'), fixed('track'), any(1)],
    suggestedContacts: 'Local bank, state agricultural department, feed merchants.',
  },
  {
    id: 'federal-agent',
    name: 'Federal Agent',
    description: 'G-man of the Bureau or Treasury enforcing federal law.',
    points: { kind: 'edu2plus', other: ['DEX', 'STR'] },
    creditRating: { min: 20, max: 40 },
    slots: [fixed('drive-auto'), fixed('fighting-brawl'), fixed('firearms-handgun'), fixed('law'), fixed('persuade'), fixed('stealth'), fixed('spot-hidden'), any(1)],
    suggestedContacts: 'Bureau colleagues, US attorneys, local police, informants.',
  },
  {
    id: 'fence',
    name: 'Fence',
    description: 'Middleman who turns stolen goods into clean cash.',
    points: { kind: 'edu2plus', other: ['APP'] },
    creditRating: { min: 20, max: 40 },
    slots: [fixed('accounting'), fixed('appraise'), fixed('art-craft', 'Forgery'), interpersonal(2), fixed('history'), fixed('spot-hidden'), any(1)],
    suggestedContacts: 'Burglars, pawnbrokers, jewelers, crooked auctioneers.',
  },
  {
    id: 'firefighter',
    name: 'Firefighter',
    description: 'Smoke-eater of the city fire brigade.',
    points: { kind: 'edu2plus', other: ['DEX', 'STR'] },
    creditRating: { min: 9, max: 30 },
    slots: [fixed('climb'), fixed('dodge'), fixed('drive-auto'), fixed('first-aid'), fixed('jump'), fixed('mechanical-repair'), fixed('operate-heavy-machinery'), fixed('throw')],
    suggestedContacts: 'Firehouse comrades, police, ambulance crews, city hall.',
  },
  {
    id: 'foreign-correspondent',
    name: 'Foreign Correspondent',
    description: 'Reporter filing dispatches from distant capitals and war zones.',
    points: { kind: 'edu4' },
    creditRating: { min: 10, max: 40 },
    slots: [fixed('history'), interpersonal(2), fixed('language-other'), fixed('language-own'), fixed('listen'), fixed('psychology'), any(1)],
    suggestedContacts: 'Embassy staff, wire services, foreign officials, fixers.',
  },
  {
    id: 'forensic-surgeon',
    name: 'Forensic Surgeon',
    description: 'Medical examiner reading the stories the dead still tell.',
    points: { kind: 'edu4' },
    creditRating: { min: 40, max: 60 },
    slots: [fixed('language-other', 'Latin'), fixed('library-use'), fixed('medicine'), fixed('persuade'), fixed('science', 'Biology'), fixed('science', 'Forensics'), fixed('spot-hidden'), any(1)],
    suggestedContacts: 'Coroners, police detectives, district attorneys, morgue staff.',
  },
  {
    id: 'forger',
    name: 'Forger / Counterfeiter',
    description: 'Artist whose masterpieces bear other people’s signatures.',
    points: { kind: 'edu4' },
    creditRating: { min: 20, max: 60 },
    slots: [fixed('accounting'), fixed('appraise'), fixed('art-craft', 'Forgery'), fixed('history'), fixed('library-use'), fixed('sleight-of-hand'), fixed('spot-hidden'), any(1)],
    suggestedContacts: 'Organized crime, document dealers, engravers, fences.',
  },
  {
    id: 'gambler',
    name: 'Gambler',
    description: 'Professional player of cards, dice and long odds.',
    points: { kind: 'edu2plus', other: ['APP', 'DEX'] },
    creditRating: { min: 8, max: 50 },
    slots: [fixed('accounting'), fixed('art-craft', 'Acting'), interpersonal(2), fixed('listen'), fixed('psychology'), fixed('sleight-of-hand'), fixed('spot-hidden')],
    suggestedContacts: 'Bookies, casino staff, loan sharks, fellow players.',
  },
  {
    id: 'gangster-boss',
    name: 'Gangster Boss',
    description: 'Head of a criminal outfit, feared and obeyed.',
    points: { kind: 'edu2plus', other: ['APP'] },
    creditRating: { min: 60, max: 95 },
    slots: [fixed('fighting-brawl'), fixed('firearms-handgun'), fixed('law'), fixed('listen'), interpersonal(2), fixed('psychology'), fixed('spot-hidden')],
    suggestedContacts: 'Underlings, corrupt officials, lawyers, rival outfits.',
  },
  {
    id: 'gentleman',
    name: 'Gentleman / Lady',
    description: 'Well-bred member of the leisured classes, at home in society.',
    points: { kind: 'edu2plus', other: ['APP'] },
    creditRating: { min: 40, max: 90 },
    slots: [fixed('art-craft'), fixed('charm'), fixed('persuade'), fixed('firearms-rifle-shotgun'), fixed('history'), fixed('language-other'), fixed('ride'), any(1)],
    suggestedContacts: 'Society families, clubs, servants, tenants, politicians.',
  },
  {
    id: 'gun-moll',
    name: 'Gun Moll',
    description: 'Sharp-eyed companion to gangsters, no mere ornament.',
    points: { kind: 'edu2plus', other: ['APP'] },
    creditRating: { min: 10, max: 80 },
    slots: [fixed('art-craft'), interpersonal(2), fixed('drive-auto'), oneOf('Fighting (Brawl) or Firearms (Handgun)', 'fighting-brawl', 'firearms-handgun'), fixed('listen'), fixed('stealth'), any(1)],
    suggestedContacts: 'Gangsters, nightclub staff, police on the take.',
  },
  {
    id: 'hobo',
    name: 'Hobo',
    description: 'Itinerant worker riding the rails from job to job.',
    points: { kind: 'edu2plus', other: ['APP', 'DEX'] },
    creditRating: { min: 0, max: 5 },
    slots: [fixed('art-craft'), fixed('climb'), fixed('jump'), fixed('listen'), oneOf('Locksmith or Sleight of Hand', 'locksmith', 'sleight-of-hand'), fixed('navigate'), fixed('stealth'), interpersonal(1)],
    suggestedContacts: 'Fellow travelers, rail yard workers, soup kitchens.',
  },
  {
    id: 'hospital-orderly',
    name: 'Hospital Orderly',
    description: 'Ward worker who sees everything the doctors miss.',
    points: { kind: 'edu2plus', other: ['STR'] },
    creditRating: { min: 6, max: 15 },
    slots: [fixed('electrical-repair'), fixed('fighting-brawl'), fixed('first-aid'), interpersonal(2), fixed('listen'), fixed('mechanical-repair'), fixed('stealth')],
    suggestedContacts: 'Hospital staff, patients, ambulance crews, pharmacists.',
  },
  {
    id: 'journalist',
    name: 'Journalist',
    description: 'Reporter chasing stories for the papers or wire services.',
    points: { kind: 'edu4' },
    creditRating: { min: 9, max: 30 },
    slots: [fixed('art-craft', 'Photography'), fixed('history'), fixed('library-use'), fixed('language-own'), interpersonal(1), fixed('psychology'), any(2)],
    suggestedContacts: 'News industry colleagues, editors, police, politicians, street sources.',
  },
  {
    id: 'judge',
    name: 'Judge',
    description: 'Arbiter of the law from the high bench.',
    points: { kind: 'edu4' },
    creditRating: { min: 50, max: 80 },
    slots: [fixed('history'), interpersonal(2), fixed('law'), fixed('library-use'), fixed('listen'), fixed('language-own'), fixed('psychology')],
    suggestedContacts: 'The bar, court officials, politicians, law schools.',
  },
  {
    id: 'laboratory-assistant',
    name: 'Laboratory Assistant',
    description: 'Junior scientist minding the beakers and the records.',
    points: { kind: 'edu4' },
    creditRating: { min: 10, max: 30 },
    slots: [fixed('electrical-repair'), fixed('language-other'), fixed('library-use'), fixed('science', 'Chemistry'), fixed('science'), fixed('spot-hidden'), any(2)],
    suggestedContacts: 'Universities, research staff, chemical suppliers.',
  },
  {
    id: 'laborer',
    name: 'Laborer, Unskilled',
    description: 'Strong back for hire — docks, factories, road gangs.',
    points: { kind: 'edu2plus', other: ['DEX', 'STR'] },
    creditRating: { min: 9, max: 30 },
    slots: [fixed('drive-auto'), fixed('electrical-repair'), fixed('fighting-brawl'), fixed('first-aid'), fixed('mechanical-repair'), fixed('operate-heavy-machinery'), fixed('throw'), any(1)],
    suggestedContacts: 'Work crews, union men, foremen, dive bars.',
  },
  {
    id: 'lawyer',
    name: 'Lawyer',
    description: 'Attorney versed in the law and its loopholes.',
    points: { kind: 'edu4' },
    creditRating: { min: 30, max: 80 },
    slots: [fixed('accounting'), fixed('law'), fixed('library-use'), interpersonal(2), fixed('psychology'), any(2)],
    suggestedContacts: 'Organized crime, financiers, district attorneys, judges.',
  },
  {
    id: 'librarian',
    name: 'Librarian',
    description: 'Custodian of books and the knowledge they hold.',
    points: { kind: 'edu4' },
    creditRating: { min: 9, max: 35 },
    slots: [fixed('accounting'), fixed('library-use'), fixed('language-other'), fixed('language-own'), any(4)],
    suggestedContacts: 'Booksellers, community groups, scholars, patrons.',
  },
  {
    id: 'mechanic',
    name: 'Mechanic / Skilled Tradesperson',
    description: 'Master of engines, wiring, pipes or presses.',
    points: { kind: 'edu2plus', other: ['DEX'] },
    creditRating: { min: 9, max: 40 },
    slots: [fixed('art-craft'), fixed('drive-auto'), fixed('electrical-repair'), fixed('mechanical-repair'), fixed('operate-heavy-machinery'), any(3)],
    suggestedContacts: 'Garages, parts suppliers, union locals, customers.',
  },
  {
    id: 'military-officer',
    name: 'Military Officer',
    description: 'Commissioned officer, serving or retired.',
    points: { kind: 'edu2plus', other: ['DEX', 'STR'] },
    creditRating: { min: 20, max: 70 },
    slots: [fixed('accounting'), fixed('firearms-handgun'), fixed('navigate'), fixed('first-aid'), interpersonal(2), fixed('psychology'), any(1)],
    suggestedContacts: 'Military brass, veterans, government officials.',
  },
  {
    id: 'missionary',
    name: 'Missionary',
    description: 'Bringer of faith and medicine to far-flung places.',
    points: { kind: 'edu4' },
    creditRating: { min: 0, max: 30 },
    slots: [fixed('art-craft'), fixed('first-aid'), fixed('mechanical-repair'), fixed('medicine'), fixed('natural-world'), interpersonal(1), any(2)],
    suggestedContacts: 'Church authorities, foreign officials, local converts.',
  },
  {
    id: 'mountain-climber',
    name: 'Mountain Climber',
    description: 'Alpinist drawn to summits few have seen.',
    points: { kind: 'edu2plus', other: ['DEX', 'STR'] },
    creditRating: { min: 30, max: 60 },
    slots: [fixed('climb'), fixed('first-aid'), fixed('jump'), fixed('listen'), fixed('navigate'), oneOf('Language (Other) or Survival (Alpine)', 'language-other', 'survival'), fixed('track'), any(1)],
    suggestedContacts: 'Alpine clubs, guides, outfitters, patrons, park rangers.',
  },
  {
    id: 'museum-curator',
    name: 'Museum Curator',
    description: 'Guardian of a collection whose oldest pieces are best left crated.',
    points: { kind: 'edu4' },
    creditRating: { min: 10, max: 30 },
    slots: [fixed('accounting'), fixed('appraise'), fixed('archaeology'), fixed('history'), fixed('library-use'), fixed('occult'), fixed('language-other'), fixed('spot-hidden')],
    suggestedContacts: 'Scholars, donors, dealers, university departments.',
  },
  {
    id: 'musician',
    name: 'Musician',
    description: 'Player of instruments in clubs, orchestras or on the street.',
    points: { kind: 'edu2plus', other: ['DEX', 'POW'] },
    creditRating: { min: 9, max: 30 },
    slots: [fixed('art-craft', 'Instrument'), interpersonal(1), fixed('listen'), fixed('psychology'), any(4)],
    suggestedContacts: 'Club owners, musicians’ union, organized crime, radio stations.',
  },
  {
    id: 'nurse',
    name: 'Nurse',
    description: 'Ward professional keeping patients alive and doctors honest.',
    points: { kind: 'edu4' },
    creditRating: { min: 9, max: 30 },
    slots: [fixed('first-aid'), fixed('listen'), fixed('medicine'), interpersonal(1), fixed('psychology'), fixed('science', 'Biology'), fixed('science', 'Chemistry'), fixed('spot-hidden')],
    suggestedContacts: 'Doctors, hospital staff, patients, pharmacists.',
  },
  {
    id: 'occultist',
    name: 'Occultist',
    description: 'Student of hidden lore, séances and secret traditions.',
    points: { kind: 'edu4' },
    creditRating: { min: 9, max: 65 },
    slots: [fixed('anthropology'), fixed('history'), fixed('library-use'), fixed('occult'), fixed('language-other'), fixed('science', 'Astronomy'), any(2)],
    suggestedContacts: 'Esoteric societies, booksellers, mediums, wealthy seekers.',
  },
  {
    id: 'outdoorsman',
    name: 'Outdoorsman / Outdoorswoman',
    description: 'Guide, trapper or woodsman at home far from town.',
    points: { kind: 'edu2plus', other: ['DEX', 'STR'] },
    creditRating: { min: 5, max: 20 },
    slots: [fixed('firearms-rifle-shotgun'), fixed('first-aid'), fixed('listen'), fixed('natural-world'), fixed('navigate'), fixed('spot-hidden'), fixed('survival'), fixed('track')],
    suggestedContacts: 'Hunters, game wardens, rural families, outfitters.',
  },
  {
    id: 'parapsychologist',
    name: 'Parapsychologist',
    description: 'Investigator of hauntings, mediums and psychic phenomena.',
    points: { kind: 'edu4' },
    creditRating: { min: 9, max: 30 },
    slots: [fixed('anthropology'), fixed('art-craft', 'Photography'), fixed('history'), fixed('library-use'), fixed('occult'), fixed('language-other'), fixed('psychology'), any(1)],
    suggestedContacts: 'Universities, parapsychological societies, wealthy clients, mediums.',
  },
  {
    id: 'pharmacist',
    name: 'Pharmacist',
    description: 'Dispenser of remedies, tonics and the occasional poison.',
    points: { kind: 'edu4' },
    creditRating: { min: 35, max: 75 },
    slots: [fixed('accounting'), fixed('first-aid'), fixed('language-other', 'Latin'), fixed('library-use'), interpersonal(1), fixed('psychology'), fixed('science', 'Pharmacy'), fixed('science', 'Chemistry')],
    suggestedContacts: 'Doctors, patients, drug wholesalers, hospitals.',
  },
  {
    id: 'photographer',
    name: 'Photographer',
    description: 'Studio artist or press shooter chasing the perfect frame.',
    points: { kind: 'edu4' },
    creditRating: { min: 9, max: 30 },
    slots: [fixed('art-craft', 'Photography'), fixed('science', 'Chemistry'), fixed('psychology'), fixed('spot-hidden'), fixed('stealth'), interpersonal(1), any(2)],
    suggestedContacts: 'Newspapers, studios, chemists, subjects high and low.',
  },
  {
    id: 'pilot',
    name: 'Pilot',
    description: 'Aviator flying mail routes, charters or barnstorming shows.',
    points: { kind: 'edu2plus', other: ['DEX'] },
    creditRating: { min: 20, max: 70 },
    slots: [fixed('electrical-repair'), fixed('mechanical-repair'), fixed('navigate'), fixed('operate-heavy-machinery'), fixed('pilot', 'Aircraft'), fixed('science', 'Astronomy'), any(2)],
    suggestedContacts: 'Airfield staff, old military comrades, aircraft manufacturers.',
  },
  {
    id: 'police-detective',
    name: 'Police Detective',
    description: 'Plainclothes investigator working homicides and rackets.',
    points: { kind: 'edu2plus', other: ['DEX', 'STR'] },
    creditRating: { min: 20, max: 50 },
    slots: [oneOf('Art/Craft (Acting) or Disguise', 'art-craft', 'disguise'), fixed('firearms-handgun'), fixed('law'), fixed('listen'), interpersonal(1), fixed('psychology'), fixed('spot-hidden'), any(1)],
    suggestedContacts: 'Police colleagues, street criminals, coroners, the DA’s office.',
  },
  {
    id: 'police-officer',
    name: 'Police Officer',
    description: 'Uniformed cop walking a beat or patrolling in a prowl car.',
    points: { kind: 'edu2plus', other: ['DEX', 'STR'] },
    creditRating: { min: 9, max: 30 },
    slots: [fixed('fighting-brawl'), fixed('firearms-handgun'), fixed('first-aid'), interpersonal(1), fixed('law'), fixed('psychology'), fixed('spot-hidden'), oneOf('Drive Auto or Ride', 'drive-auto', 'ride')],
    suggestedContacts: 'Fellow officers, local businesses, street contacts, organized crime.',
  },
  {
    id: 'private-investigator',
    name: 'Private Investigator',
    description: 'Licensed gumshoe handling divorce work and missing persons.',
    points: { kind: 'edu2plus', other: ['DEX', 'STR'] },
    creditRating: { min: 9, max: 30 },
    slots: [fixed('art-craft', 'Photography'), fixed('disguise'), fixed('law'), fixed('library-use'), interpersonal(1), fixed('psychology'), fixed('spot-hidden'), any(1)],
    suggestedContacts: 'Police, clients, lowlifes who owe a favor.',
  },
  {
    id: 'professor',
    name: 'Professor',
    description: 'University academic and published authority in a field.',
    points: { kind: 'edu4' },
    creditRating: { min: 20, max: 70 },
    slots: [fixed('library-use'), fixed('language-other'), fixed('language-own'), fixed('psychology'), any(4)],
    suggestedContacts: 'Scholars, universities, libraries, museums.',
  },
  {
    id: 'prospector',
    name: 'Prospector',
    description: 'Solitary hunter of gold, oil and other buried promises.',
    points: { kind: 'edu2plus', other: ['DEX', 'STR'] },
    creditRating: { min: 0, max: 10 },
    slots: [fixed('climb'), fixed('first-aid'), fixed('history'), fixed('mechanical-repair'), fixed('natural-world'), fixed('navigate'), fixed('science', 'Geology'), fixed('spot-hidden')],
    suggestedContacts: 'Assay offices, mining companies, general stores, old-timers.',
  },
  {
    id: 'psychiatrist',
    name: 'Psychiatrist',
    description: 'Physician of the mind, licensed to treat its darkest corners.',
    points: { kind: 'edu4' },
    creditRating: { min: 30, max: 80 },
    slots: [fixed('language-other'), fixed('listen'), fixed('medicine'), fixed('persuade'), fixed('psychoanalysis'), fixed('psychology'), fixed('science', 'Biology'), any(1)],
    suggestedContacts: 'Hospitals, asylums, wealthy patients, medical journals.',
  },
  {
    id: 'psychologist',
    name: 'Psychologist',
    description: 'Analyst of behavior, in the clinic or the university.',
    points: { kind: 'edu4' },
    creditRating: { min: 10, max: 40 },
    slots: [fixed('accounting'), fixed('library-use'), fixed('listen'), fixed('persuade'), fixed('psychoanalysis'), fixed('psychology'), any(2)],
    suggestedContacts: 'Patients, academic colleagues, social workers.',
  },
  {
    id: 'researcher',
    name: 'Researcher',
    description: 'Professional digger through archives, records and stacks.',
    points: { kind: 'edu4' },
    creditRating: { min: 9, max: 30 },
    slots: [fixed('history'), fixed('library-use'), interpersonal(1), fixed('language-other'), fixed('spot-hidden'), any(3)],
    suggestedContacts: 'Librarians, archivists, academics, publishers.',
  },
  {
    id: 'sailor-commercial',
    name: 'Sailor, Commercial',
    description: 'Merchant seaman or fisherman working coastal and deep waters.',
    points: { kind: 'edu2plus', other: ['DEX', 'STR'] },
    creditRating: { min: 20, max: 40 },
    slots: [fixed('first-aid'), fixed('mechanical-repair'), fixed('natural-world'), fixed('navigate'), fixed('pilot', 'Boat'), fixed('spot-hidden'), fixed('swim'), any(1)],
    suggestedContacts: 'Shipping lines, harbormasters, dockworkers, smugglers.',
  },
  {
    id: 'sailor-naval',
    name: 'Sailor, Naval',
    description: 'Rating or petty officer of the peacetime navy.',
    points: { kind: 'edu2plus', other: ['DEX', 'STR'] },
    creditRating: { min: 9, max: 30 },
    slots: [
      oneOf('Electrical or Mechanical Repair', 'electrical-repair', 'mechanical-repair'),
      fixed('fighting-brawl'),
      fixed('firearms-rifle-shotgun'),
      fixed('first-aid'),
      fixed('navigate'),
      fixed('pilot', 'Boat'),
      fixed('survival', 'Sea'),
      fixed('swim'),
    ],
    suggestedContacts: 'Shipmates, naval bases, veterans, port authorities.',
  },
  {
    id: 'salesperson',
    name: 'Salesperson',
    description: 'Door-to-door drummer or showroom closer, always on commission.',
    points: { kind: 'edu2plus', other: ['APP'] },
    creditRating: { min: 9, max: 40 },
    slots: [fixed('accounting'), fixed('drive-auto'), interpersonal(2), fixed('listen'), fixed('psychology'), oneOf('Stealth or Sleight of Hand', 'stealth', 'sleight-of-hand'), any(1)],
    suggestedContacts: 'Customers, sales managers, hotel clerks, travelers.',
  },
  {
    id: 'scientist',
    name: 'Scientist',
    description: 'Researcher probing the frontiers of a chosen discipline.',
    points: { kind: 'edu4' },
    creditRating: { min: 9, max: 50 },
    slots: [
      oneOf('a Science specialization', 'science'),
      oneOf('a second Science specialization', 'science'),
      oneOf('a third Science specialization', 'science'),
      fixed('library-use'),
      fixed('language-other'),
      fixed('language-own'),
      fixed('spot-hidden'),
      interpersonal(1),
    ],
    suggestedContacts: 'Universities, laboratories, journals, industrial sponsors.',
  },
  {
    id: 'secretary',
    name: 'Secretary',
    description: 'Office professional who actually runs the boss’s affairs.',
    points: { kind: 'edu2plus', other: ['APP', 'DEX'] },
    creditRating: { min: 9, max: 30 },
    slots: [fixed('accounting'), fixed('art-craft', 'Typing & Shorthand'), interpersonal(2), fixed('language-own'), fixed('library-use'), fixed('psychology'), any(1)],
    suggestedContacts: 'The boss’s circle, office staff, switchboard operators.',
  },
  {
    id: 'sex-worker',
    name: 'Sex Worker',
    description: 'Survivor of the demimonde, wise to every kind of client.',
    points: { kind: 'edu2plus', other: ['APP'] },
    creditRating: { min: 5, max: 50 },
    slots: [fixed('art-craft'), interpersonal(2), fixed('dodge'), fixed('psychology'), fixed('sleight-of-hand'), fixed('stealth'), any(1)],
    suggestedContacts: 'Street contacts, madams, police, clients with secrets.',
  },
  {
    id: 'shopkeeper',
    name: 'Shopkeeper',
    description: 'Proprietor of a corner store, pharmacy or curio shop.',
    points: { kind: 'edu2plus', other: ['APP'] },
    creditRating: { min: 20, max: 40 },
    slots: [fixed('accounting'), interpersonal(2), fixed('electrical-repair'), fixed('listen'), fixed('mechanical-repair'), fixed('psychology'), fixed('spot-hidden')],
    suggestedContacts: 'Neighborhood residents, suppliers, beat cops, traveling salesmen.',
  },
  {
    id: 'smuggler',
    name: 'Smuggler',
    description: 'Mover of contraband past borders and blockades.',
    points: { kind: 'edu2plus', other: ['APP', 'DEX'] },
    creditRating: { min: 20, max: 60 },
    slots: [
      fixed('firearms-handgun'),
      fixed('listen'),
      fixed('navigate'),
      interpersonal(1),
      fixed('psychology'),
      fixed('sleight-of-hand'),
      fixed('spot-hidden'),
      oneOf('Drive Auto or Pilot (Boat)', 'drive-auto', 'pilot'),
    ],
    suggestedContacts: 'Coast guard on the take, buyers, foreign suppliers, fishermen.',
  },
  {
    id: 'soldier',
    name: 'Soldier',
    description: 'Enlisted fighting man, serving or lately returned from the Great War.',
    points: { kind: 'edu2plus', other: ['DEX', 'STR'] },
    creditRating: { min: 9, max: 30 },
    slots: [
      oneOf('Climb or Swim', 'climb', 'swim'),
      fixed('dodge'),
      fixed('fighting-brawl'),
      fixed('firearms-rifle-shotgun'),
      fixed('stealth'),
      fixed('survival'),
      {
        kind: 'choice',
        count: 2,
        from: ['first-aid', 'mechanical-repair', 'language-other'],
        label: 'two of First Aid, Mech. Repair or Language (Other)',
      },
    ],
    suggestedContacts: 'Veterans’ associations, old comrades in arms.',
  },
  {
    id: 'spy',
    name: 'Spy',
    description: 'Agent of a foreign power — or of one’s own, watching the foreigners.',
    points: { kind: 'edu2plus', other: ['APP', 'DEX'] },
    creditRating: { min: 20, max: 60 },
    slots: [
      oneOf('Art/Craft (Acting) or Disguise', 'art-craft', 'disguise'),
      fixed('firearms-handgun'),
      fixed('listen'),
      fixed('language-other'),
      interpersonal(1),
      fixed('psychology'),
      fixed('sleight-of-hand'),
      fixed('stealth'),
    ],
    suggestedContacts: 'Handlers, embassy staff, informants, forgers.',
  },
  {
    id: 'street-punk',
    name: 'Street Punk',
    description: 'Corner tough running errands for bigger fish.',
    points: { kind: 'edu2plus', other: ['DEX'] },
    creditRating: { min: 3, max: 10 },
    slots: [fixed('climb'), fixed('fighting-brawl'), fixed('firearms-handgun'), fixed('jump'), fixed('sleight-of-hand'), fixed('stealth'), fixed('throw'), any(1)],
    suggestedContacts: 'Gangs, pawnbrokers, other punks, the local fixer.',
  },
  {
    id: 'student',
    name: 'Student / Intern',
    description: 'Scholar-in-training at a university, hospital or firm.',
    points: { kind: 'edu4' },
    creditRating: { min: 5, max: 10 },
    slots: [
      oneOf('Language (Own or Other)', 'language-own', 'language-other'),
      fixed('library-use'),
      fixed('listen'),
      any(3), // three fields of study
      any(2),
    ],
    suggestedContacts: 'Professors, fellow students, family sponsors.',
  },
  {
    id: 'stuntman',
    name: 'Stunt Performer',
    description: 'Daredevil doubling for the stars when the script turns dangerous.',
    points: { kind: 'edu2plus', other: ['DEX', 'STR'] },
    creditRating: { min: 10, max: 50 },
    slots: [
      fixed('climb'),
      fixed('dodge'),
      oneOf('Electrical or Mechanical Repair', 'electrical-repair', 'mechanical-repair'),
      fixed('fighting-brawl'),
      fixed('first-aid'),
      fixed('jump'),
      fixed('swim'),
      any(1),
    ],
    suggestedContacts: 'Film studios, directors, other stunt performers, medics.',
  },
  {
    id: 'taxi-driver',
    name: 'Taxi Driver',
    description: 'Hack who knows every street and half the secrets in the city.',
    points: { kind: 'edu2plus', other: ['DEX'] },
    creditRating: { min: 9, max: 30 },
    slots: [fixed('accounting'), fixed('drive-auto'), fixed('electrical-repair'), fixed('fast-talk'), fixed('mechanical-repair'), fixed('navigate'), fixed('spot-hidden'), any(1)],
    suggestedContacts: 'Dispatchers, hotel doormen, cops, night owls of every stripe.',
  },
  {
    id: 'teacher',
    name: 'Teacher',
    description: 'Schoolmaster or mistress shaping the town’s young minds.',
    points: { kind: 'edu4' },
    creditRating: { min: 9, max: 30 },
    slots: [fixed('language-own'), fixed('library-use'), fixed('listen'), interpersonal(1), fixed('psychology'), any(3)],
    suggestedContacts: 'Parents, school boards, former pupils, local clergy.',
  },
  {
    id: 'tribe-member',
    name: 'Tribe Member',
    description: 'Member of a traditional community living close to the old ways.',
    points: { kind: 'edu2plus', other: ['DEX', 'STR'] },
    creditRating: { min: 0, max: 15 },
    slots: [fixed('climb'), oneOf('Fighting or Throw', 'fighting-brawl', 'throw'), fixed('natural-world'), fixed('listen'), fixed('occult'), fixed('spot-hidden'), fixed('swim'), fixed('survival')],
    suggestedContacts: 'Fellow tribe members, tribal elders.',
  },
  {
    id: 'undertaker',
    name: 'Undertaker',
    description: 'Mortician tending the town’s dead with quiet dignity.',
    points: { kind: 'edu4' },
    creditRating: { min: 20, max: 40 },
    slots: [fixed('accounting'), fixed('drive-auto'), fixed('history'), interpersonal(1), fixed('occult'), fixed('psychology'), fixed('science', 'Biology'), fixed('science', 'Chemistry')],
    suggestedContacts: 'Bereaved families, clergy, coroners, gravediggers.',
  },
  {
    id: 'union-activist',
    name: 'Union Activist',
    description: 'Organizer fighting for the working stiff, against long odds.',
    points: { kind: 'edu4' },
    creditRating: { min: 5, max: 30 },
    slots: [fixed('accounting'), interpersonal(2), fixed('fighting-brawl'), fixed('law'), fixed('listen'), fixed('operate-heavy-machinery'), fixed('psychology')],
    suggestedContacts: 'Union locals, sympathetic journalists, radicals, strikebreakers’ spies.',
  },
  {
    id: 'waitstaff',
    name: 'Waiter / Waitress',
    description: 'Server in a diner, supper club or hotel restaurant.',
    points: { kind: 'edu2plus', other: ['APP', 'DEX'] },
    creditRating: { min: 9, max: 20 },
    slots: [fixed('accounting'), fixed('art-craft'), interpersonal(2), fixed('dodge'), fixed('listen'), fixed('psychology'), any(1)],
    suggestedContacts: 'Regular customers, kitchen staff, the manager’s connections.',
  },
  {
    id: 'zealot',
    name: 'Zealot',
    description: 'Impassioned crusader for a cause, faith or ideology.',
    points: { kind: 'edu2plus', other: ['APP', 'POW'] },
    creditRating: { min: 0, max: 30 },
    slots: [fixed('history'), interpersonal(2), fixed('psychology'), fixed('stealth'), any(3)],
    suggestedContacts: 'Religious or political groups, fellow believers, the press.',
  },
  {
    id: 'zookeeper',
    name: 'Zookeeper',
    description: 'Keeper of captive beasts, common and otherwise.',
    points: { kind: 'edu4' },
    creditRating: { min: 9, max: 40 },
    slots: [fixed('animal-handling'), fixed('accounting'), fixed('dodge'), fixed('first-aid'), fixed('natural-world'), fixed('medicine'), fixed('science', 'Zoology'), fixed('science', 'Pharmacy')],
    suggestedContacts: 'Veterinarians, animal dealers, circus folk, zoological societies.',
  },
]

const byId = new Map(OCCUPATIONS.map((o) => [o.id, o]))

export function occupationById(id: string): Occupation {
  const occupation = byId.get(id)
  if (!occupation) throw new Error(`Unknown occupation: ${id}`)
  return occupation
}
