import { INTERPERSONAL_SKILL_IDS, type Occupation, type OccupationSkillSlot } from './types'

const interpersonal = (count: number): OccupationSkillSlot => ({
  kind: 'choice',
  count,
  from: INTERPERSONAL_SKILL_IDS,
  label: count === 1 ? 'one interpersonal skill' : `${count} interpersonal skills`,
})

const fixed = (skillId: string, spec?: string): OccupationSkillSlot =>
  spec ? { kind: 'fixed', skillId, spec } : { kind: 'fixed', skillId }

const oneOf = (label: string, ...from: string[]): OccupationSkillSlot => ({
  kind: 'choice',
  count: 1,
  from,
  label,
})

const any = (count: number): OccupationSkillSlot => ({ kind: 'any', count })

/**
 * Core 7e occupations (1920s). Descriptions are our own summaries.
 * Every occupation also buys Credit Rating from occupation points,
 * within the listed range.
 */
export const OCCUPATIONS: readonly Occupation[] = [
  {
    id: 'accountant',
    name: 'Accountant',
    description: 'Keeper of ledgers and finder of financial irregularities.',
    points: { kind: 'edu4' },
    creditRating: { min: 30, max: 70 },
    slots: [fixed('accounting'), fixed('law'), fixed('library-use'), fixed('listen'), interpersonal(1), fixed('psychology'), fixed('spot-hidden'), any(1)],
    suggestedContacts: 'Business associates, lawyers, financial sector colleagues.',
  },
  {
    id: 'antiquarian',
    name: 'Antiquarian',
    description: 'Collector and student of old and curious things.',
    points: { kind: 'edu4' },
    creditRating: { min: 30, max: 70 },
    slots: [fixed('appraise'), fixed('art-craft'), fixed('history'), fixed('library-use'), fixed('language-other'), interpersonal(1), fixed('spot-hidden'), any(1)],
    suggestedContacts: 'Booksellers, antique dealers, historical societies, museums.',
  },
  {
    id: 'artist',
    name: 'Artist',
    description: 'Painter, sculptor or other creator of works of art.',
    points: { kind: 'edu2plus', other: ['DEX', 'POW'] },
    creditRating: { min: 9, max: 50 },
    slots: [fixed('art-craft'), oneOf('History or Natural World', 'history', 'natural-world'), interpersonal(1), fixed('language-other'), fixed('psychology'), fixed('spot-hidden'), any(2)],
    suggestedContacts: 'Art galleries, critics, wealthy patrons, the advertising industry.',
  },
  {
    id: 'athlete',
    name: 'Athlete',
    description: 'Professional or gentleman sportsman in peak condition.',
    points: { kind: 'edu2plus', other: ['DEX', 'STR'] },
    creditRating: { min: 9, max: 70 },
    slots: [fixed('climb'), fixed('jump'), fixed('fighting-brawl'), fixed('ride'), interpersonal(1), fixed('swim'), fixed('throw'), any(1)],
    suggestedContacts: 'Sports clubs, sportswriters, other athletes, coaches.',
  },
  {
    id: 'author',
    name: 'Author',
    description: 'Writer of novels, stories or verse, often on the trail of inspiration.',
    points: { kind: 'edu4' },
    creditRating: { min: 9, max: 30 },
    slots: [fixed('art-craft', 'Literature'), fixed('history'), fixed('library-use'), oneOf('Natural World or Occult', 'natural-world', 'occult'), fixed('language-other'), fixed('language-own'), fixed('psychology'), any(1)],
    suggestedContacts: 'Publishers, editors, critics, other writers.',
  },
  {
    id: 'clergy',
    name: 'Member of the Clergy',
    description: 'Ordained minister, priest or rabbi tending a flock.',
    points: { kind: 'edu4' },
    creditRating: { min: 9, max: 60 },
    slots: [fixed('accounting'), fixed('history'), fixed('library-use'), fixed('listen'), fixed('language-other'), interpersonal(1), fixed('psychology'), any(1)],
    suggestedContacts: 'Church hierarchy, local congregations, community leaders.',
  },
  {
    id: 'criminal',
    name: 'Criminal',
    description: 'Burglar, con artist, bootlegger or freelance villain.',
    points: { kind: 'edu2plus', other: ['DEX', 'STR'] },
    creditRating: { min: 5, max: 65 },
    slots: [
      interpersonal(1),
      fixed('psychology'),
      fixed('spot-hidden'),
      fixed('stealth'),
      {
        kind: 'choice',
        count: 4,
        from: ['appraise', 'disguise', 'fighting-brawl', 'firearms-handgun', 'locksmith', 'mechanical-repair', 'sleight-of-hand'],
        label: 'four specialisms of the trade',
      },
    ],
    suggestedContacts: 'The underworld, fences, corrupt officials, other criminals.',
  },
  {
    id: 'dilettante',
    name: 'Dilettante',
    description: 'Person of independent means free to pursue their whims.',
    points: { kind: 'edu2plus', other: ['APP'] },
    creditRating: { min: 50, max: 99 },
    slots: [fixed('art-craft'), fixed('firearms-handgun'), fixed('language-other'), fixed('ride'), interpersonal(1), any(3)],
    suggestedContacts: 'High society, old family friends, artists and hangers-on.',
  },
  {
    id: 'doctor',
    name: 'Doctor of Medicine',
    description: 'Physician, surgeon or medical researcher.',
    points: { kind: 'edu4' },
    creditRating: { min: 30, max: 80 },
    slots: [fixed('first-aid'), fixed('language-other', 'Latin'), fixed('medicine'), fixed('psychology'), fixed('science', 'Biology'), fixed('science', 'Pharmacy'), any(2)],
    suggestedContacts: 'Patients, hospital staff, medical colleagues, nurses.',
  },
  {
    id: 'drifter',
    name: 'Drifter',
    description: 'Wanderer living hand to mouth on the road.',
    points: { kind: 'edu2plus', other: ['APP', 'DEX', 'STR'] },
    creditRating: { min: 0, max: 5 },
    slots: [fixed('climb'), fixed('jump'), fixed('listen'), fixed('navigate'), interpersonal(1), fixed('stealth'), any(2)],
    suggestedContacts: 'Other drifters, freight yard workers, rural folk met on the road.',
  },
  {
    id: 'engineer',
    name: 'Engineer',
    description: 'Designer and builder of machines, structures and systems.',
    points: { kind: 'edu4' },
    creditRating: { min: 30, max: 60 },
    slots: [fixed('art-craft', 'Technical Drawing'), fixed('electrical-repair'), fixed('library-use'), fixed('mechanical-repair'), fixed('operate-heavy-machinery'), fixed('science', 'Engineering'), any(2)],
    suggestedContacts: 'Industrialists, military contacts, city planners, workshops.',
  },
  {
    id: 'entertainer',
    name: 'Entertainer',
    description: 'Actor, singer, dancer or vaudeville performer.',
    points: { kind: 'edu2plus', other: ['APP'] },
    creditRating: { min: 9, max: 70 },
    slots: [fixed('art-craft', 'Acting'), fixed('disguise'), interpersonal(2), fixed('listen'), fixed('psychology'), any(2)],
    suggestedContacts: 'Theatre people, film studios, newspapers, organized crime.',
  },
  {
    id: 'farmer',
    name: 'Farmer',
    description: 'Owner or worker of a farm, wise in the ways of land and weather.',
    points: { kind: 'edu2plus', other: ['DEX', 'STR'] },
    creditRating: { min: 9, max: 30 },
    slots: [fixed('art-craft', 'Farming'), fixed('drive-auto'), interpersonal(1), fixed('mechanical-repair'), fixed('natural-world'), fixed('operate-heavy-machinery'), fixed('track'), any(1)],
    suggestedContacts: 'Local bank, state agricultural department, feed merchants.',
  },
  {
    id: 'journalist',
    name: 'Journalist',
    description: 'Reporter chasing stories for the papers or wire services.',
    points: { kind: 'edu4' },
    creditRating: { min: 9, max: 30 },
    slots: [fixed('art-craft', 'Photography'), fixed('history'), fixed('library-use'), fixed('language-own'), interpersonal(1), fixed('psychology'), any(2)],
    suggestedContacts: 'News industry colleagues, editors, police, politicians, street sources.',
  },
  {
    id: 'lawyer',
    name: 'Lawyer',
    description: 'Attorney versed in the law and its loopholes.',
    points: { kind: 'edu4' },
    creditRating: { min: 30, max: 80 },
    slots: [fixed('accounting'), fixed('law'), fixed('library-use'), interpersonal(2), fixed('psychology'), any(2)],
    suggestedContacts: 'Organized crime, financiers, district attorneys, judges.',
  },
  {
    id: 'librarian',
    name: 'Librarian',
    description: 'Custodian of books and the knowledge they hold.',
    points: { kind: 'edu4' },
    creditRating: { min: 9, max: 35 },
    slots: [fixed('accounting'), fixed('library-use'), fixed('language-other'), fixed('language-own'), any(4)],
    suggestedContacts: 'Booksellers, community groups, scholars, patrons.',
  },
  {
    id: 'military-officer',
    name: 'Military Officer',
    description: 'Commissioned officer, serving or retired.',
    points: { kind: 'edu2plus', other: ['DEX', 'STR'] },
    creditRating: { min: 20, max: 70 },
    slots: [fixed('accounting'), fixed('firearms-handgun'), fixed('navigate'), fixed('first-aid'), interpersonal(2), fixed('psychology'), any(1)],
    suggestedContacts: 'Military brass, veterans, government officials.',
  },
  {
    id: 'missionary',
    name: 'Missionary',
    description: 'Bringer of faith and medicine to far-flung places.',
    points: { kind: 'edu4' },
    creditRating: { min: 0, max: 30 },
    slots: [fixed('art-craft'), fixed('first-aid'), fixed('mechanical-repair'), fixed('medicine'), fixed('natural-world'), interpersonal(1), any(2)],
    suggestedContacts: 'Church authorities, foreign officials, local converts.',
  },
  {
    id: 'musician',
    name: 'Musician',
    description: 'Player of instruments in clubs, orchestras or on the street.',
    points: { kind: 'edu2plus', other: ['DEX', 'POW'] },
    creditRating: { min: 9, max: 30 },
    slots: [fixed('art-craft', 'Instrument'), interpersonal(1), fixed('listen'), fixed('psychology'), any(4)],
    suggestedContacts: 'Club owners, musicians’ union, organized crime, radio stations.',
  },
  {
    id: 'parapsychologist',
    name: 'Parapsychologist',
    description: 'Investigator of hauntings, mediums and psychic phenomena.',
    points: { kind: 'edu4' },
    creditRating: { min: 9, max: 30 },
    slots: [fixed('anthropology'), fixed('art-craft', 'Photography'), fixed('history'), fixed('library-use'), fixed('occult'), fixed('language-other'), fixed('psychology'), any(1)],
    suggestedContacts: 'Universities, parapsychological societies, wealthy clients, mediums.',
  },
  {
    id: 'pilot',
    name: 'Pilot',
    description: 'Aviator flying mail routes, charters or barnstorming shows.',
    points: { kind: 'edu2plus', other: ['DEX'] },
    creditRating: { min: 20, max: 70 },
    slots: [fixed('electrical-repair'), fixed('mechanical-repair'), fixed('navigate'), fixed('operate-heavy-machinery'), fixed('pilot', 'Aircraft'), fixed('science', 'Astronomy'), any(2)],
    suggestedContacts: 'Airfield staff, old military comrades, aircraft manufacturers.',
  },
  {
    id: 'police-detective',
    name: 'Police Detective',
    description: 'Plainclothes investigator working homicides and rackets.',
    points: { kind: 'edu2plus', other: ['DEX', 'STR'] },
    creditRating: { min: 20, max: 50 },
    slots: [oneOf('Art/Craft (Acting) or Disguise', 'art-craft', 'disguise'), fixed('firearms-handgun'), fixed('law'), fixed('listen'), interpersonal(1), fixed('psychology'), fixed('spot-hidden'), any(1)],
    suggestedContacts: 'Police colleagues, street criminals, coroners, the DA’s office.',
  },
  {
    id: 'police-officer',
    name: 'Police Officer',
    description: 'Uniformed cop walking a beat or patrolling in a prowl car.',
    points: { kind: 'edu2plus', other: ['DEX', 'STR'] },
    creditRating: { min: 9, max: 30 },
    slots: [fixed('fighting-brawl'), fixed('firearms-handgun'), fixed('first-aid'), interpersonal(1), fixed('law'), fixed('psychology'), fixed('spot-hidden'), oneOf('Drive Auto or Ride', 'drive-auto', 'ride')],
    suggestedContacts: 'Fellow officers, local businesses, street contacts, organized crime.',
  },
  {
    id: 'private-investigator',
    name: 'Private Investigator',
    description: 'Licensed gumshoe handling divorce work and missing persons.',
    points: { kind: 'edu2plus', other: ['DEX', 'STR'] },
    creditRating: { min: 9, max: 30 },
    slots: [fixed('art-craft', 'Photography'), fixed('disguise'), fixed('law'), fixed('library-use'), interpersonal(1), fixed('psychology'), fixed('spot-hidden'), any(1)],
    suggestedContacts: 'Police, clients, lowlifes who owe a favor.',
  },
  {
    id: 'professor',
    name: 'Professor',
    description: 'University academic and published authority in a field.',
    points: { kind: 'edu4' },
    creditRating: { min: 20, max: 70 },
    slots: [fixed('library-use'), fixed('language-other'), fixed('language-own'), fixed('psychology'), any(4)],
    suggestedContacts: 'Scholars, universities, libraries, museums.',
  },
  {
    id: 'soldier',
    name: 'Soldier',
    description: 'Enlisted fighting man, serving or lately returned from the Great War.',
    points: { kind: 'edu2plus', other: ['DEX', 'STR'] },
    creditRating: { min: 9, max: 30 },
    slots: [
      oneOf('Climb or Swim', 'climb', 'swim'),
      fixed('dodge'),
      fixed('fighting-brawl'),
      fixed('firearms-rifle-shotgun'),
      fixed('stealth'),
      fixed('survival'),
      {
        kind: 'choice',
        count: 2,
        from: ['first-aid', 'mechanical-repair', 'language-other'],
        label: 'two of First Aid, Mech. Repair or Language (Other)',
      },
    ],
    suggestedContacts: 'Veterans’ associations, old comrades in arms.',
  },
  {
    id: 'tribe-member',
    name: 'Tribe Member',
    description: 'Member of a traditional community living close to the old ways.',
    points: { kind: 'edu2plus', other: ['DEX', 'STR'] },
    creditRating: { min: 0, max: 15 },
    slots: [fixed('climb'), oneOf('Fighting or Throw', 'fighting-brawl', 'throw'), fixed('natural-world'), fixed('listen'), fixed('occult'), fixed('spot-hidden'), fixed('swim'), fixed('survival')],
    suggestedContacts: 'Fellow tribe members, tribal elders.',
  },
  {
    id: 'zealot',
    name: 'Zealot',
    description: 'Impassioned crusader for a cause, faith or ideology.',
    points: { kind: 'edu2plus', other: ['APP', 'POW'] },
    creditRating: { min: 0, max: 30 },
    slots: [fixed('history'), interpersonal(2), fixed('psychology'), fixed('stealth'), any(3)],
    suggestedContacts: 'Religious or political groups, fellow believers, the press.',
  },
]

const byId = new Map(OCCUPATIONS.map((o) => [o.id, o]))

export function occupationById(id: string): Occupation {
  const occupation = byId.get(id)
  if (!occupation) throw new Error(`Unknown occupation: ${id}`)
  return occupation
}
